<!doctype html>
<html lang="zh-cn">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge;chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no">
    <link rel="icon" type="image/x-icon" href="/media/image_web/favicon.ico"/>
    <link rel="stylesheet" href="media/share/one2.css" type="text/css" media="screen" />
    <meta name="description" content="全国唯一民主、自由、科学的私密大学校园社区——囊括大学同学八卦、朋友圈爆料、DotaA宅校花男神怪咖奇葩"/>
    <meta name="keywords" content="课程格子, 超级课程表, 友秘, 悄悄, 乌鸦, 抱抱, 叽叽, 哔哔, 无秘, 呵呵, 匿名, 大街, 飞信, 人人, 微密"/>
    <meta name="keywords" content="地图, 1024, 唱吧, 美团, 音乐, 天气, 淘宝, 京东, 聚美, 头条, 乐视, 奇艺, 优酷, 搜狐, 贴吧, 新闻, 动漫、MT, 游戏"/>
    <meta name="keywords" content="大学英语1, 大学英语2, 大学英语3, 大学英语4, 思想道德修养, 法律基础, 军事理论, 毛泽东思想概论, 邓小平理论, 马克思主义政治经济学, 计算机文化基础, 高等数学, 线性代数, 大学物理, 概率论与数理统计, 物理实验, 微积分, 近代物理, 校园助手微信, 个性网, 大学生招聘, 实习, 招生, 高考查询, 四级查询, 苍井空, 吴亦凡, 海贼王, 火影忍者, 快乐大本营, 12306, NBA, dota2, dnf, lol"/>
    <meta name="author" content="校园秘密APP"/>
    <title>{{ title }}</title>
</head>
<body>
<div class="wrapper">
    <div class="main">
        <div class="secret">



            <div class="bg" style="z-index:2">
                <div class="pic"><img  src="{{logo}}" alt="校园秘密app"></div>
                <div class="bottom2">
                     <div class="slogan1">校园秘密</div>
                     <div class="slogan2">中国最大的私密校园社区</div>
                </div>
                    <!-- <a href="https://itunes.apple.com/cn/app/qiao-qiao-you-mi-mi-qiao-qiao/id870466235?mt=8" class="download iphone">
                        <span ><img src=""></span>
                     </a>-->

                <div class="downloadlink">
                    <a href="http://xiaoyuanmimi.com/download/android/CampusSecret.apk" class="download android">
                        <span class="left" ><b ></span>
                        <span class="right">Android&nbsp;版<br>立即下载</span>
                    </a>
                </div>


                </div>

        </div>
        <div class="comments2">
            <div class="text">
                <ul>
                    <li>
                        <div class="container">
                            <div class="portrait"><img src="{{introduction1}}"></div>
                            <div class="content">
                                <p>{{ comment1 }}</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="container">
                            <div class="portrait"><img src="{{introduction2}}"></div>
                            <div class="content">
                                <p>{{ comment2 }}</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="container2">
                            <div class="portrait"><img src="{{introduction3}}"></div>
                            <div class="content">
                                <p>{{ comment3 }}</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="container2">
                            <div class="portrait"><img src="{{introduction4}}"></div>
                            <div class="content">
                                <p>{{ comment4 }}</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="end">
            <p>
                校园秘密APP&nbsp;©&nbsp;2014&nbsp;&nbsp;-&nbsp;&nbsp;
                <a href="mailto:m@xiaoyuanmimi.com?subject=【校园秘密APP】意见反馈" style="text-decoration: none; color: white;">联系我们</a>
            </p>
            <p >
                客服邮箱:&nbsp;
                <a href="mailto:m@xiaoyuanmimi.com?subject=【校园秘密APP】意见反馈" style="text-decoration: none; color: white;">m@xiaoyuanmimi.com</a>&nbsp;&nbsp;-&nbsp;&nbsp;QQ:&nbsp;2601610750

            </p>
        </div>
    </div>
</div>

<div style="display:none">
    <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1252985173'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1252985173%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
</div>
</body>
</html>