<!doctype html>
<html lang="zh-cn">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge;chrome=1">
    <meta name="viewport" content="width=951px, initial-scale=1.0, minimum-scale=0.1, maximum-scale=10.0, user-scalable=yes"/>
    <link rel="icon" type="image/x-icon" href="/media/image_web/favicon.ico"/>
    <link rel="stylesheet" href="media/share/index.css" type="text/css" media="screen" />
    <meta name="description" content="全国唯一民主、自由、科学的私密大学校园社区——囊括大学同学八卦、朋友圈爆料、DotaA宅校花男神怪咖奇葩"/>
    <meta name="keywords" content="学习, 作业, 酒店, 四六级, 兼职, 爆料, 八卦, 实习, 外卖, 星座, 考试, 小说, 火车票, 团购"/>
    <meta name="keywords" content="微博, 微信, 美图秀秀, 大姨妈, 大众点评, 陌陌, 快播, 优酷, 58, 赶集, 百度, QQ, 电影, 地图, 腾讯, 美拍, 月经, 高德, 携程, 万年历, 酷狗, 内涵"/>
    <meta name="keywords" content="大学英语1, 大学英语2, 大学英语3, 大学英语4, 思想道德修养, 法律基础, 军事理论, 毛泽东思想概论, 邓小平理论, 马克思主义政治经济学, 计算机文化基础, 高等数学, 线性代数, 大学物理, 概率论与数理统计, 物理实验, 微积分, 近代物理, 校园助手微信, 个性网, 大学生招聘, 实习, 招生, 高考查询, 四级查询, 苍井空, 吴亦凡, 海贼王, 火影忍者, 快乐大本营, 12306, NBA, dota2, dnf, lol"/>
    <meta name="author" content="校园秘密APP"/>
    <title>校园秘密APP</title>
</head>

<body>
    <div class="all">
       <div class="spread">
           <div class="spread1">
               <div class="spread2">
                   校园秘密APP
               </div>
              <!-- <div class="spread3">
                   <a href="">Sign In</a>
               </div>-->
           </div>
       </div>
       <div class="secret">

               <div class="bg" style="z-index:2">
                   <div class="pic2"><img  src="/media/image_web/index.png" alt="校园秘密app"></div>
                    <div class="pic"><img  src="{{logo}}"></div>
                    <div class="bottom2">
                        <div class="slogan1">校园秘密</div>
                        <div class="slogan2">中国最大的私密校园社区</div>
                    </div>
                    <!-- <a href="https://itunes.apple.com/cn/app/qiao-qiao-you-mi-mi-qiao-qiao/id870466235?mt=8" class="download iphone">
                        <span ><img src=""></span>
                     </a>-->
                   <div class="bottom1">
                        <div class="downloadlink">
                            <a href="http://xiaoyuanmimi.com/download/android/CampusSecret.apk" class="download android">
                            <span class="left" ></span>
                            <span class="right">Android&nbsp版<br>立即下载</span>
                            </a>
                        </div>

                        <div class="downloadlink2">
                            <div href="" class="download iphone">
                            <span class="left" ></span>
                            <span class="right">iPhone&nbsp版<br>即将发布</span>
                            </div>
                        </div>
                        <div class="erweima">
                            <div class="pic3"></div>
                            扫描二维码下载
                        </div>

                   </div>

            </div>

        </div>
        <div class="comments2">
            <div class="text">

                        <div class="container">
                            <div class="portrait"><img src="{{introduction1}}"></div>
                            <div class="content">
                                <p>{{ comment1 }}</p>
                            </div>
                        </div>

                        <div class="container">
                            <div class="portrait"><img src="{{introduction2}}"></div>
                            <div class="content">
                                <p>{{ comment2 }}</p>
                            </div>
                        </div>

                        <div class="container">
                            <div class="portrait"><img src="{{introduction3}}"></div>
                            <div class="content">
                                <p>{{ comment3 }}</p>
                            </div>
                        </div>

                        <div class="container">
                            <div class="portrait"><img src="{{introduction4}}"></div>
                            <div class="content">
                                <p>{{ comment4 }}</p>
                            </div>
                        </div>

            </div>
        </div>
        <div class="end">
            <p class="p1">
                校园秘密APP&nbsp;©&nbsp;2014&nbsp;&nbsp;-&nbsp;&nbsp;客服邮箱:&nbsp;<a href="mailto:m@xiaoyuanmimi.com?subject=【校园秘密APP】意见反馈" style="text-decoration: none; color: white;">m@xiaoyuanmimi.com</a>&nbsp;&nbsp;-&nbsp;&nbsp;QQ:&nbsp;2601610750

                <!--<a href="http://weibo.com/u/5147488806" style="text-decoration: none; color: white;">联系我们</a>-->
            </p>
            <p> 京ICP证14027336号<!--&nbsp;&nbsp;-&nbsp;&nbsp;京公网安备1100000000000000?号--></p>

        </div>
    </div>

    <div style="display:none">
        <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1252985173'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1252985173%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
    </div>
</body>
</html>