<!doctype html>
<html lang="zh-cn">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <link rel="icon" type="image/x-icon" href="/media/image_web/favicon.ico"/>
    <link rel="stylesheet" href="media/share/weixindownload.css" type="text/css" media="screen" />
    <script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
    <script type="text/javascript">
            var ua = navigator.userAgent.toLowerCase();
            if(ua.match("MicroMessenger") == null) {
               window.location.href = "http://xiaoyuanmimi.com/download/android/CampusSecret.apk";
            }
    </script>

    <title>校园秘密APP</title>
</head>

<body>
    <div class="img1" ></div>
    <div class="wall">
        <div class="row1">
            <div class="line1">1&nbsp;&nbsp;点击右上角跳转按钮</div>
            <div class="line2"><div class="bg" ></div></div>
            <div class="line2">2&nbsp;&nbsp;选择在浏览器中打开</div>
            <div class="line2"><div class="bg"></div></div>
            <div class="line2">即可下载校园秘密APP</div>
        </div>
        <div class="row2">
            <div class="line1">
                    <div class="img2" ></div>
            </div>
            <div class="line2">
                <div class="img3" ></div>
            </div>
            <div class="line2">
                <div class="img4" ></div>
            </div>
        </div>
    </div>
    <div style="display:none">
        <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1252985173'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1252985173%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
    </div>
</body>
</html>