<!doctype html>
<html lang="zh-cn">
<head>
<base href="/" />
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
<meta name="format-detection" content="telephone=no">
<link rel="icon" type="image/x-icon" href="/images/favicon.ico"/>
<link rel="stylesheet" href="media/share/one.css" type="text/css" media="screen" />

<title>{{ title }}</title>
</head>
<body>
    <div class="wrapper">
        <div class="main1">
<br/>
校园秘密社区公约（试行）<br/>
<br/>
一、我们不欢迎下列信息：<br/>
<br/>
1. 暴力色情，主要表现为：<br/>
（1）具体描绘性行为或露骨宣扬色情的淫秽信息。<br/>
（2）露三点的图片，带有色情意味、暗示、挑逗和引起他人类似感受的文字。<br/>
（3）宣扬暴力血腥，及其他道德上令人反感、引起普遍不适的内容。<br/>
<br/>
2. 广告欺诈，主要表现为：<br/>
（1）商业广告或促销等劝诱资料。<br/>
（2）诈骗，或向对方进行敲诈勒索。<br/>
（3）以确定的口吻传播不确定的信息。<br/>
（4）传播已被澄清的谣言。<br/>
（5）通过机器或软件等手段大量发送的垃圾信息、重复文字。<br/>
<br/>
3. 人身攻击，主要表现为：<br/>
（1）用粗俗、攻击性等语言点名辱骂、恶意中伤其他人。点名特指通过提及对方真实姓名、普遍周知的昵称、体貌特征，或者公布住址等信息并且依据该信息可以直接联想到某具体人，或者直接使用对方照片。<br/>
（2）刻意捏造信息诽谤他人名誉，冒充其他任何人或机构。<br/>
（3）泄露他人隐私，以及侵犯他人合法权益的其他行为。<br/>
（4）人肉搜索或以其它方式骚扰他人。<br/>
（5）因民族、种族、宗教、性取向、性别、年龄、地域、生理特征、受教育背景等归类而歧视、侮辱他人，挑起争端。<br/>
<br/>
4. 违反法律法规，主要表现为：<br/>
（1）反对宪法确定的基本原则。<br/>
（2）危害国家统一、主权和领土完整，颠覆国家政权。<br/>
（3）泄露国家秘密、危害国家安全或者损害国家荣誉和利益。<br/>
（4）煽动民族仇恨、民族歧视、破坏民族团结，或者侵害民族风俗、习惯。<br/>
（5）破坏国家宗教政策，宣扬邪教、迷信。<br/>
（6）散布谣言，扰乱社会秩序，破坏社会稳定。<br/>
（7）宣扬赌博、暴力、凶杀、恐怖或者教唆犯罪。<br/>
（8）煽动非法集会、结社、游行、示威、聚众扰乱社会秩序。<br/>
（9）含有中国法律、法规、规章、条例以及任何具有法律效力的规范所限制或禁止的其它内容。<br/>
<br/>
二、处理违规信息和用户<br/>
<br/>
任何上述违规的秘密或评论，我们都将予以审核并删除。<br/>
违规信息被删除后，作者将受到警告，严重违规和警告无效者将被禁言（视情况封禁3-14天）。<br/>
若您被禁言，请耐心等待封禁时间结束（不可提前解封）。此后不要再发布违规信息，否则将被封禁更长时间直至永久禁言。<br/>
<br/>
同时，若您看到上述违规秘密或评论，请尽快点击“举报”按钮，我们将在举报后1个工作日内核实并完成处理。若您认为被系统删除的内容不属于上述情形，可通过意见反馈详述您的看法。<br/>
<br/>
校园秘密致力为您创造出一片真诚、友善的天空，希望大家都能尊重他人、关爱他人，一起维护来之不易的社区氛围。
            <br/>
            <br/>
        </div>
    </div>
    <script>
        if (/Mobile/i.test(navigator.userAgent)) {
            var secretEle = document.querySelector('.secret');
            secretEle.style.height = document.documentElement.clientWidth + 'px';
        }
    </script>
    </body>
</html>