<!doctype html>
<html lang="zh-cn">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no">
    <link rel="icon" type="image/x-icon" href="/media/image_web/favicon.ico"/>
    <link rel="stylesheet" href="media/share/secret.css" type="text/css" media="screen" />
    <script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function(){
               var x = $("div.app-download").offset().top;
               if(($(window).width() > 480) && (x > $(window).height())){
                   $("div.app-download").css({"position":"fixed","bottom":"0","margin":"0"});
                    $("a.btn-more").css({"margin-bottom":"112px"});
               }
               else{
                    $("a.btn-more").css({"margin-bottom":"72px"});
               };
            var ua = navigator.userAgent.toLowerCase();
            if(ua.match(/MicroMessenger/i)=="micromessenger") {
               $("#appAd").attr("href","http://xiaoyuanmimi.com/index/weixindownload")
            }
        })
    </script>

<title>{{ title }}</title>
</head>
<body>
    <div class="wrapper">
        <div class="main">
            <div class="secret">
                <div class="bg" ><img sytle="opacity:0.6" src="{{ background}}"/></div>
                <table>
                    <tr>
                        <td><div class="content">{{ secret }}</div></td>
                    </tr>
                </table>
                <div class="bottom">
                    <div class="circle">{{school_name}}</div>
                    <div class="relates">
                        <div class="comment-count">
                            <i class="i i-comment"></i>
                            <span class="num">{{ comment_count }}</span>
                                </div>
                        <div class="liked-count">
                            <i class="i i-like"></i>
                            <span class="num">{{ liked_count }}</span>
                                </div>
                    </div>
                </div>
            </div>
            <div class="comments">
                <ul>
                	{% for comment in comments %}
                		<li>
                        <div class="container">
                            <div class="portrait"><div class="head"><img src="media/avatar/{{comment.avatar}}"></div></div>
                            <div class="content">
                                <p>{{ comment.content|e }}</p>
                                <div>
                                    {{ comment.floor|e }}楼 · {{comment.rel_time}}</div>
                            </div>
                        </div>
                    	</li>

                	{% endfor %}
                		
                </ul>
                <a href="/" class="btn-more" ></a>
                <div class="app-download">
                    <a href="http://xiaoyuanmimi.com/download/android/CampusSecret.apk" id="appAd">
                        <div class="pic">
                            <img src="/media/image/logo120_web.png"/>
                        </div>
                        <div class="text">
                            <div class="slogan1">
                                校园秘密
                            </div>
                            <div class="slogan2">
                                看看朋友圈同学的八卦、爆料、真心话
                            </div>
                        </div>
                        <div id="weixin" class="btn"><div class="icon-down-bold"></div>免费安装</div>

                    </a>
                </div>
                </div>

        </div>
    </div>
    <script>
        if (/Mobile/i.test(navigator.userAgent)) {
            var secretEle = document.querySelector('.secret');
            secretEle.style.height = document.documentElement.clientWidth + 'px';
        }
    </script>
    <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-49515307-1', 'wumii.org');
        ga('send', 'pageview');
    </script>
    <div style="display:none">
        <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1252985173'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1252985173%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
    </div>
</body>
</html>