<div class="span12" file="tab-add-secret.phtml" widget-class="AddSecretTabPane" widget-id="add-secret-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>发布秘密</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
                    <li><a href="#added_secrets_tab"  class="adminSecrets" data-toggle="tab">已发布</a></li>
                    <li class="active"><a href="#add_secret_tab" data-toggle="tab">发布</a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="add_secret_tab">
                        <div class="content" style="width:320px;height:320px;margin:10px;padding:3px;font-size:24px;font-weight:bold;border:1px dashed" contenteditable="true">
                        </div>
                        <!--  /* Now we do not need post secret with photo by admin */
                        <a class="btn blue photo" href="javascript:">添加照片</a>
                        -->
                        <div class="box01-num">
                            <p>你还可以输入<b class="num">120</b>字</p>
                        </div>
                        <a class="btn blue publish" href="javascript:">发布</a>
                        <div class="progress progress-striped active" style="width:50%;margin:10px 0">
                            <div class="bar" style="width: 0%;"></div>
                        </div>
                        <div style="margin-top: 10px" widget-class="SchoolSelectorEx" widget-id="add-secrets-school-selector"></div>
					</div>
                    <div class="tab-pane" id="added_secrets_tab">
                        <div class="added_published_secrets_tab"></div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
