<div class="span6" file="tab1.phtml" widget-class="AdminSchoolsPane" widget-id="admin-schools-pane">
    <div class="portlet box blue tabbable">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i>学校管理</div>
        </div>
        <div class="portlet-body">
            <div class="tabbable portlet-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#admin_schools_tab" data-toggle="tab" tab="man">管理</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="admin_schools_tab">
                        <div class="schools">
                            <input style="margin: 5px" type="text" class="search-school" placeholder="查找学校"/>
                            <a class="btn blue search-school">查找</a>
                            <a class="btn blue add-school" style="display:none">添加</a>
                            <a class="btn blue del-school" style="display:none">删除学校</a>
                            <div widget-class="SchoolSelector" widget-id="adminschools-secrets-school-selector" style="float:right"></div>
                        </div>
                        <div class="academy">
                            <input style="margin: 5px" type="text" class="academy" placeholder="添加学院"/>
                            <a class="btn blue add-academy">添加</a>
                        </div>

                        <div class="academylist"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
