<div class="span6" file="tab1.phtml" widget-class="" widget-id="advise-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>意见反馈</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#advise_tab2" data-toggle="tab" tab="del">未处理</a></li>
                    <li><a href="#advise_tab1" data-toggle="tab" tab="pub">已处理</a></li>
				</ul>
				<div class="tab-content">

					<div class="tab-pane active" id="advise_tab1">

					</div>
					<div class="tab-pane" id="advise_tab2">

					</div>

				</div>
			</div>
		</div>
	</div>
</div>
