<div class="span6 hidden-phone" file="tab1.phtml" widget-class="CommentsTabPane" widget-id="comments-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>评论</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#comments_tab" data-toggle="tab">评论</a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="comments_tab">

					</div>

				</div>
			</div>
		</div>
	</div>
</div>
