<div class="span6" file="tab1.phtml" widget-class="RedisTabPane" widget-id="redis-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>Redis</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
					<li><a href="#portlet_tab2" data-toggle="tab" tab="del">已删除</a></li>
                    <li class="active"><a href="#portlet_tab1" data-toggle="tab" tab="pub">已发布</a></li>
				</ul>
				<div class="tab-content">

					<div class="tab-pane active" id="portlet_tab1">
						<div class="secret-list"></div>
					</div>
					<div class="tab-pane" id="portlet_tab2">
						<div id="secret-list-del">
						</div>
					</div>


				</div>
			</div>
		</div>
	</div>
</div>
