<div class="span6" file="tab1.phtml" widget-class="SecretsTabPane" widget-id="secrets-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>秘密</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
					<li><a class="deleted2" href="#portlet_tab2" data-toggle="tab" tab="del">已删除</a></li>
                    <li class="active"><a class="published" href="#portlet_tab1" data-toggle="tab" tab="pub">已发布</a></li>
				</ul>
				<div class="tab-content">
                    <div widget-class="SchoolSelector" widget-id="secrets-school-selector">
                    </div>
					<div class="tab-pane active" id="portlet_tab1">
						<div class="secret-list"></div>
					</div>
					<div class="tab-pane" id="portlet_tab2">
						<div class="secret-list-del"></div>
					</div>


				</div>
			</div>
		</div>
	</div>
</div>
