<div class="span6" file="tab1.phtml" widget-class="SessionsTabPane" widget-id="sessions-tab-pane">
	<div class="portlet box blue tabbable">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>Sessions</div>
		</div>
		<div class="portlet-body">
			<div class="tabbable portlet-tabs">
				<ul class="nav nav-tabs">
					<li><a href="#session_tab1" data-toggle="tab" tab="del">已登录</a></li>

				</ul>
				<div class="tab-content">

					<div class="tab-pane active" id="session_tab1">
						<a class="btn blue session-count">刷新</a>
					</div>



				</div>
			</div>
		</div>
	</div>
</div>
