<!-- sidebar.phtml -->
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar nav-collapse collapse">
	<!-- BEGIN SIDEBAR MENU -->        
	<ul class="page-sidebar-menu">
		<li>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<div class="sidebar-toggler hidden-phone"></div>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
		</li>

		<!-- 审核 -->
		<li class="start active">
			<a href="index.html">
			<i class="icon-home"></i> 
			<span class="title">审核</span>
			<span class="selected"></span>
			</a>
			<ul class="sub-menu">
				<li>
					<a href="#report-secret-row">被举报的秘密</a>
				</li>
				<li >
					<a href="#report-comment-row">被举报的评论</a>
				</li>
                <li class="first-row-entry">
                    <a href="#secret-row">秘密</a>
                </li>
                <li >
                    <a href="#advise-row">投诉和建议</a>
                </li>
			</ul>			
		</li>

		<!-- 运营 -->
		<li class="start">
			<a href="index.html">
			<i class="icon-home"></i> 
			<span class="title">运营</span>
			<span class="selected"></span>
			</a>
			<ul class="sub-menu">
				<li>
					<a href="#add-secret-row">添加秘密</a>
				</li>
                <li>
                    <a href="#add-question-row">添加提问</a>
                </li>
			</ul>			
		</li>

        <!-- 管理 -->
        <li class="start">
            <a href="index.html">
                <i class="icon-home"></i>
                <span class="title">管理</span>
                <span class="selected"></span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="#admin-man-row">账号管理</a>
                </li>
                <li>
                    <a href="#admin-schools-row">学校管理</a>
                </li>
                <li>
                    <a href="#admin-versions-row">版本管理</a>
                </li>
            </ul>
        </li>

        <!-- 开发 -->
        <li class="start">
            <a href="index.html">
                <i class="icon-home"></i>
                <span class="title">开发</span>
                <span class="selected"></span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="#dev-row">Redis</a>
                </li>
            </ul>
        </li>
	</ul>
	<!-- END SIDEBAR MENU -->
</div>
<!-- END SIDEBAR -->